export const ADD_ALL_COUNTRIES = "ADD_ALL_COUNTRIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY"
export const GET_ALL_CONTINENTS = "GET_ALL_CONTINENTS"
export const SAVE_FILTERS = "SAVE_FILTERS"
export const INPUT_FORM_FILTER = "INPUT_FORM_FILTER"