export const ADD_ALL_COUNTRIES = "ADD_ALL_COUNTRIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";